#!/bin/bash

bspc config border_width        5
bspc config window_gap          20
bspc monitor -d I II III IV V VI VII VIII IX X
 
bspc config top_padding 14 

# Visual options
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#45282a"
bspc config active_border_color "#344633"
bspc config focused_border_color "#606c78"
bspc config presel_border_color "#344633"
bspc config urgent_border_color "#6e322a"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

# Rules
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a feh floating=on manage=off

~/.config/bspwm/panel/panel &
